export const DOC_PER_PAGE = 10;
export const nations = [
  { nationality: "Afghan", flag: "https://flagcdn.com/af.svg" },
  { nationality: "Albanian", flag: "https://flagcdn.com/al.svg" },
  { nationality: "Algerian", flag: "https://flagcdn.com/dz.svg" },
  { nationality: "Andorran", flag: "https://flagcdn.com/ad.svg" },
  { nationality: "Angolan", flag: "https://flagcdn.com/ao.svg" },
  { nationality: "Antiguan", flag: "https://flagcdn.com/ag.svg" },
  { nationality: "Argentine", flag: "https://flagcdn.com/ar.svg" },
  { nationality: "Armenian", flag: "https://flagcdn.com/am.svg" },
  { nationality: "Australian", flag: "https://flagcdn.com/au.svg" },
  { nationality: "Austrian", flag: "https://flagcdn.com/at.svg" },
  { nationality: "Azerbaijani", flag: "https://flagcdn.com/az.svg" },
  { nationality: "Bahamian", flag: "https://flagcdn.com/bs.svg" },
  { nationality: "Bahraini", flag: "https://flagcdn.com/bh.svg" },
  { nationality: "Bangladeshi", flag: "https://flagcdn.com/bd.svg" },
  { nationality: "Barbadian", flag: "https://flagcdn.com/bb.svg" },
  { nationality: "Belarusian", flag: "https://flagcdn.com/by.svg" },
  { nationality: "Belgian", flag: "https://flagcdn.com/be.svg" },
  { nationality: "Belizean", flag: "https://flagcdn.com/bz.svg" },
  { nationality: "Beninese", flag: "https://flagcdn.com/bj.svg" },
  { nationality: "Bhutanese", flag: "https://flagcdn.com/bt.svg" },
  { nationality: "Bolivian", flag: "https://flagcdn.com/bo.svg" },
  { nationality: "Bosnian", flag: "https://flagcdn.com/ba.svg" },
  { nationality: "Botswanan", flag: "https://flagcdn.com/bw.svg" },
  { nationality: "Brazilian", flag: "https://flagcdn.com/br.svg" },
  { nationality: "Bruneian", flag: "https://flagcdn.com/bn.svg" },
  { nationality: "Bulgarian", flag: "https://flagcdn.com/bg.svg" },
  { nationality: "Burkinabe", flag: "https://flagcdn.com/bf.svg" },
  { nationality: "Burundian", flag: "https://flagcdn.com/bi.svg" },
  { nationality: "Cabo Verdean", flag: "https://flagcdn.com/cv.svg" },
  { nationality: "Cambodian", flag: "https://flagcdn.com/kh.svg" },
  { nationality: "Cameroonian", flag: "https://flagcdn.com/cm.svg" },
  { nationality: "Canadian", flag: "https://flagcdn.com/ca.svg" },
  { nationality: "Central African", flag: "https://flagcdn.com/cf.svg" },
  { nationality: "Chadian", flag: "https://flagcdn.com/td.svg" },
  { nationality: "Chilean", flag: "https://flagcdn.com/cl.svg" },
  { nationality: "Chinese", flag: "https://flagcdn.com/cn.svg" },
  { nationality: "Colombian", flag: "https://flagcdn.com/co.svg" },
  { nationality: "Comorian", flag: "https://flagcdn.com/km.svg" },
  { nationality: "Congolese", flag: "https://flagcdn.com/cg.svg" },
  { nationality: "Costa Rican", flag: "https://flagcdn.com/cr.svg" },
  { nationality: "Croatian", flag: "https://flagcdn.com/hr.svg" },
  { nationality: "Cuban", flag: "https://flagcdn.com/cu.svg" },
  { nationality: "Cypriot", flag: "https://flagcdn.com/cy.svg" },
  { nationality: "Czech", flag: "https://flagcdn.com/cz.svg" },
  { nationality: "Danish", flag: "https://flagcdn.com/dk.svg" },
  { nationality: "Djiboutian", flag: "https://flagcdn.com/dj.svg" },
  { nationality: "Dominican", flag: "https://flagcdn.com/do.svg" },
  { nationality: "Ecuadorian", flag: "https://flagcdn.com/ec.svg" },
  { nationality: "Egyptian", flag: "https://flagcdn.com/eg.svg" },
  { nationality: "Salvadoran", flag: "https://flagcdn.com/sv.svg" },
  { nationality: "Equatorial Guinean", flag: "https://flagcdn.com/gq.svg" },
  { nationality: "Eritrean", flag: "https://flagcdn.com/er.svg" },
  { nationality: "Estonian", flag: "https://flagcdn.com/ee.svg" },
  { nationality: "Eswatini", flag: "https://flagcdn.com/sz.svg" },
  { nationality: "Ethiopian", flag: "https://flagcdn.com/et.svg" },
  { nationality: "Fijian", flag: "https://flagcdn.com/fj.svg" },
  { nationality: "Finnish", flag: "https://flagcdn.com/fi.svg" },
  { nationality: "French", flag: "https://flagcdn.com/fr.svg" },
  { nationality: "Gabonese", flag: "https://flagcdn.com/ga.svg" },
  { nationality: "Gambian", flag: "https://flagcdn.com/gm.svg" },
  { nationality: "Georgian", flag: "https://flagcdn.com/ge.svg" },
  { nationality: "German", flag: "https://flagcdn.com/de.svg" },
  { nationality: "Ghanaian", flag: "https://flagcdn.com/gh.svg" },
  { nationality: "Greek", flag: "https://flagcdn.com/gr.svg" },
  { nationality: "Grenadian", flag: "https://flagcdn.com/gd.svg" },
  { nationality: "Guatemalan", flag: "https://flagcdn.com/gt.svg" },
  { nationality: "Guinean", flag: "https://flagcdn.com/gn.svg" },
  { nationality: "Guinea-Bissauan", flag: "https://flagcdn.com/gw.svg" },
  { nationality: "Guyanese", flag: "https://flagcdn.com/gy.svg" },
  { nationality: "Haitian", flag: "https://flagcdn.com/ht.svg" },
  { nationality: "Honduran", flag: "https://flagcdn.com/hn.svg" },
  { nationality: "Hungarian", flag: "https://flagcdn.com/hu.svg" },
  { nationality: "Icelandic", flag: "https://flagcdn.com/is.svg" },
  { nationality: "Indian", flag: "https://flagcdn.com/in.svg" },
  { nationality: "Indonesian", flag: "https://flagcdn.com/id.svg" },
  { nationality: "Iranian", flag: "https://flagcdn.com/ir.svg" },
  { nationality: "Iraqi", flag: "https://flagcdn.com/iq.svg" },
  { nationality: "Irish", flag: "https://flagcdn.com/ie.svg" },
  { nationality: "Israeli", flag: "https://flagcdn.com/il.svg" },
  { nationality: "Italian", flag: "https://flagcdn.com/it.svg" },
  { nationality: "Jamaican", flag: "https://flagcdn.com/jm.svg" },
  { nationality: "Japanese", flag: "https://flagcdn.com/jp.svg" },
  { nationality: "Jordanian", flag: "https://flagcdn.com/jo.svg" },
  { nationality: "Kazakhstani", flag: "https://flagcdn.com/kz.svg" },
  { nationality: "Kenyan", flag: "https://flagcdn.com/ke.svg" },
  { nationality: "Kiribati", flag: "https://flagcdn.com/ki.svg" },
  { nationality: "Kuwaiti", flag: "https://flagcdn.com/kw.svg" },
  { nationality: "Kyrgyzstani", flag: "https://flagcdn.com/kg.svg" },
  { nationality: "Laotian", flag: "https://flagcdn.com/la.svg" },
  { nationality: "Latvian", flag: "https://flagcdn.com/lv.svg" },
  { nationality: "Lebanese", flag: "https://flagcdn.com/lb.svg" },
  { nationality: "Lesotho", flag: "https://flagcdn.com/ls.svg" },
  { nationality: "Liberian", flag: "https://flagcdn.com/lr.svg" },
  { nationality: "Libyan", flag: "https://flagcdn.com/ly.svg" },
  { nationality: "Liechtensteiner", flag: "https://flagcdn.com/li.svg" },
  { nationality: "Lithuanian", flag: "https://flagcdn.com/lt.svg" },
  { nationality: "Luxembourgish", flag: "https://flagcdn.com/lu.svg" },
  { nationality: "Malagasy", flag: "https://flagcdn.com/mg.svg" },
  { nationality: "Malawian", flag: "https://flagcdn.com/mw.svg" },
  { nationality: "Malaysian", flag: "https://flagcdn.com/my.svg" },
  { nationality: "Maldivian", flag: "https://flagcdn.com/mv.svg" },
  { nationality: "Malian", flag: "https://flagcdn.com/ml.svg" },
  { nationality: "Maltese", flag: "https://flagcdn.com/mt.svg" },
  { nationality: "Marshallese", flag: "https://flagcdn.com/mh.svg" },
  { nationality: "Mauritanian", flag: "https://flagcdn.com/mr.svg" },
  { nationality: "Mauritian", flag: "https://flagcdn.com/mu.svg" },
  { nationality: "Mexican", flag: "https://flagcdn.com/mx.svg" },
  { nationality: "Micronesian", flag: "https://flagcdn.com/fm.svg" },
  { nationality: "Moldovan", flag: "https://flagcdn.com/md.svg" },
  { nationality: "Monégasque", flag: "https://flagcdn.com/mc.svg" },
  { nationality: "Mongolian", flag: "https://flagcdn.com/mn.svg" },
  { nationality: "Montenegrin", flag: "https://flagcdn.com/me.svg" },
  { nationality: "Moroccan", flag: "https://flagcdn.com/ma.svg" },
  { nationality: "Mozambican", flag: "https://flagcdn.com/mz.svg" },
  { nationality: "Burmese", flag: "https://flagcdn.com/mm.svg" },
  { nationality: "Namibian", flag: "https://flagcdn.com/na.svg" },
  { nationality: "Nauruan", flag: "https://flagcdn.com/nr.svg" },
  { nationality: "Nepali", flag: "https://flagcdn.com/np.svg" },
  { nationality: "Dutch", flag: "https://flagcdn.com/nl.svg" },
  { nationality: "New Zealander", flag: "https://flagcdn.com/nz.svg" },
  { nationality: "Nicaraguan", flag: "https://flagcdn.com/ni.svg" },
  { nationality: "Nigerien", flag: "https://flagcdn.com/ne.svg" },
  { nationality: "Nigerian", flag: "https://flagcdn.com/ng.svg" },
  { nationality: "North Korean", flag: "https://flagcdn.com/kp.svg" },
  { nationality: "Macedonian", flag: "https://flagcdn.com/mk.svg" },
  { nationality: "Norwegian", flag: "https://flagcdn.com/no.svg" },
  { nationality: "Omani", flag: "https://flagcdn.com/om.svg" },
  { nationality: "Pakistani", flag: "https://flagcdn.com/pk.svg" },
  { nationality: "Palauan", flag: "https://flagcdn.com/pw.svg" },
  { nationality: "Palestinian", flag: "https://flagcdn.com/ps.svg" },
  { nationality: "Panamanian", flag: "https://flagcdn.com/pa.svg" },
  { nationality: "Papua New Guinean", flag: "https://flagcdn.com/pg.svg" },
  { nationality: "Paraguayan", flag: "https://flagcdn.com/py.svg" },
  { nationality: "Peruvian", flag: "https://flagcdn.com/pe.svg" },
  { nationality: "Filipino", flag: "https://flagcdn.com/ph.svg" },
  { nationality: "Polish", flag: "https://flagcdn.com/pl.svg" },
  { nationality: "Portuguese", flag: "https://flagcdn.com/pt.svg" },
  { nationality: "Qatari", flag: "https://flagcdn.com/qa.svg" },
  { nationality: "Romanian", flag: "https://flagcdn.com/ro.svg" },
  { nationality: "Russian", flag: "https://flagcdn.com/ru.svg" },
  { nationality: "Rwandan", flag: "https://flagcdn.com/rw.svg" },
  { nationality: "Kittitian or Nevisian", flag: "https://flagcdn.com/kn.svg" },
  { nationality: "Saint Lucian", flag: "https://flagcdn.com/lc.svg" },
  { nationality: "Saint Vincentian", flag: "https://flagcdn.com/vc.svg" },
  { nationality: "Samoan", flag: "https://flagcdn.com/ws.svg" },
  { nationality: "Sammarinese", flag: "https://flagcdn.com/sm.svg" },
  { nationality: "Sao Tomean", flag: "https://flagcdn.com/st.svg" },
  { nationality: "Saudi or Saudi Arabian", flag: "https://flagcdn.com/sa.svg" },
  { nationality: "Senegalese", flag: "https://flagcdn.com/sn.svg" },
  { nationality: "Serbian", flag: "https://flagcdn.com/rs.svg" },
  { nationality: "Seychellois", flag: "https://flagcdn.com/sc.svg" },
  { nationality: "Sierra Leonean", flag: "https://flagcdn.com/sl.svg" },
  { nationality: "Singaporean", flag: "https://flagcdn.com/sg.svg" },
  { nationality: "Slovak", flag: "https://flagcdn.com/sk.svg" },
  { nationality: "Slovenian", flag: "https://flagcdn.com/si.svg" },
  { nationality: "Solomon Islander", flag: "https://flagcdn.com/sb.svg" },
  { nationality: "Somali", flag: "https://flagcdn.com/so.svg" },
  { nationality: "South African", flag: "https://flagcdn.com/za.svg" },
  { nationality: "South Sudanese", flag: "https://flagcdn.com/ss.svg" },
  { nationality: "Spanish", flag: "https://flagcdn.com/es.svg" },
  { nationality: "Sri Lankan", flag: "https://flagcdn.com/lk.svg" },
  { nationality: "Sudanese", flag: "https://flagcdn.com/sd.svg" },
  { nationality: "Surinamese", flag: "https://flagcdn.com/sr.svg" },
  { nationality: "Swedish", flag: "https://flagcdn.com/se.svg" },
  { nationality: "Swiss", flag: "https://flagcdn.com/ch.svg" },
  { nationality: "Syrian", flag: "https://flagcdn.com/sy.svg" },
  { nationality: "Taiwanese", flag: "https://flagcdn.com/tw.svg" },
  { nationality: "Tajik", flag: "https://flagcdn.com/tj.svg" },
  { nationality: "Tanzanian", flag: "https://flagcdn.com/tz.svg" },
  { nationality: "Thai", flag: "https://flagcdn.com/th.svg" },
  { nationality: "Timorese", flag: "https://flagcdn.com/tl.svg" },
  { nationality: "Togolese", flag: "https://flagcdn.com/tg.svg" },
  { nationality: "Tongan", flag: "https://flagcdn.com/to.svg" },
  { nationality: "Tobagonian", flag: "https://flagcdn.com/tt.svg" },
  { nationality: "Tunisian", flag: "https://flagcdn.com/tn.svg" },
  { nationality: "Turkish", flag: "https://flagcdn.com/tr.svg" },
  { nationality: "Turkmen", flag: "https://flagcdn.com/tm.svg" },
  { nationality: "Tuvaluan", flag: "https://flagcdn.com/tv.svg" },
  { nationality: "Ugandan", flag: "https://flagcdn.com/ug.svg" },
  { nationality: "Ukrainian", flag: "https://flagcdn.com/ua.svg" },
  { nationality: "Emirati", flag: "https://flagcdn.com/ae.svg" },
  { nationality: "British", flag: "https://flagcdn.com/gb.svg" },
  { nationality: "American", flag: "https://flagcdn.com/us.svg" },
  { nationality: "Uruguayan", flag: "https://flagcdn.com/uy.svg" },
  { nationality: "Uzbek", flag: "https://flagcdn.com/uz.svg" },
  { nationality: "Ni-Vanuatu", flag: "https://flagcdn.com/vu.svg" },
  { nationality: "Vatican", flag: "https://flagcdn.com/va.svg" },
  { nationality: "Venezuelan", flag: "https://flagcdn.com/ve.svg" },
  { nationality: "Vietnamese", flag: "https://flagcdn.com/vn.svg" },
  { nationality: "Yemeni", flag: "https://flagcdn.com/ye.svg" },
  { nationality: "Zambian", flag: "https://flagcdn.com/zm.svg" },
  { nationality: "Zimbabwean", flag: "https://flagcdn.com/zw.svg" },
];
