import { PropTypes } from "prop-types";

const GlobalTypes = {
  children: PropTypes.node,
  avatar: PropTypes.string,
  user: PropTypes.string,
  bookingId: PropTypes.string,
  bookings: PropTypes.array,
  booking: PropTypes.object,
  cabins: PropTypes.array,
  cabin: PropTypes.object,
  cabinData: PropTypes.object,
  onClose: PropTypes.func,
  sales: PropTypes.array,
  isFetching: PropTypes.bool,
  numDays: PropTypes.number,
  icon: PropTypes.node,
  title: PropTypes.string,
  loading: PropTypes.bool,
  value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  color: PropTypes.string,
  cabinsCount: PropTypes.number,
  stays: PropTypes.array,
  isFetchingBooks: PropTypes.bool,
  isFetchingStays: PropTypes.bool,
  isLoading: PropTypes.bool,
  todayActivities: PropTypes.array,
  activity: PropTypes.object,
  variation: PropTypes.string,
  to: PropTypes.string,
  as: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  size: PropTypes.string,
  type: PropTypes.string,
  disabled: PropTypes.bool,
  onClick: PropTypes.func,
  checked: PropTypes.bool,
  onChange: PropTypes.func,
  id: PropTypes.string,
  resourceName: PropTypes.string,
  onConfirm: PropTypes.func,
  logoutMessage: PropTypes.string,
  label: PropTypes.string,
  resource: PropTypes.string,
  error: PropTypes.object,
  resetErrorBoundary: PropTypes.func,
  filterField: PropTypes.string,
  options: PropTypes.array,
  data: PropTypes.array,
  render: PropTypes.func,
  name: PropTypes.string,
  columns: PropTypes.string,
  count: PropTypes.number,
  header: PropTypes.string,
  sort: PropTypes.string,
  field: PropTypes.string,
};

export default GlobalTypes;
